#!/bin/bash

# Quick Cookie Update Script
# Makes it super easy to update Jira session cookies

set -e

cd "$(dirname "$0")"

echo "🍪 Jira Cookie Updater"
echo "=" | head -c 50; echo ""
echo ""
echo "Please provide your fresh Jira session cookies:"
echo ""

# Read JSESSIONID
echo -n "📝 JSESSIONID: "
read JSESSIONID

# Read XSRF Token
echo -n "📝 atlassian.account.xsrf.token: "
read XSRF_TOKEN

# Read Tenant Session Token
echo -n "📝 tenant.session.token: "
read TENANT_TOKEN

# Write to .jira-session file
cat > .jira-session << EOF
# Jira Session Credentials
# Auto-generated by update-cookies.sh on $(date)

export JIRA_JSESSIONID=${JSESSIONID}
export JIRA_ACCOUNT_XSRF_TOKEN=${XSRF_TOKEN}
export JIRA_TENANT_SESSION_TOKEN=${TENANT_TOKEN}
EOF

echo ""
echo "✅ Cookies saved to .jira-session"
echo ""
echo "🚀 Ready to run! Choose what to do next:"
echo ""
echo "   1) Fetch all sprint data (recommended)"
echo "   2) Export recent issues only"
echo "   3) Exit (I'll run it manually)"
echo ""
echo -n "Your choice [1-3]: "
read CHOICE

case $CHOICE in
    1)
        echo ""
        echo "🚀 Running Sprint Data Fetcher..."
        echo ""
        ./run-sprint-fetcher.sh
        ;;
    2)
        echo ""
        echo "🚀 Running Jira History Exporter..."
        echo ""
        ./run-jira-exporter.sh
        ;;
    3)
        echo ""
        echo "✅ Cookies updated! Run ./run-sprint-fetcher.sh when ready."
        ;;
    *)
        echo ""
        echo "❌ Invalid choice. Cookies saved but nothing executed."
        echo "   Run ./run-sprint-fetcher.sh manually when ready."
        ;;
esac

